# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.3.0"
hooks = [
  {
    id = "codespell",
    additional_dependencies = ["tomli"]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.11.11"
hooks = [
  {
    id = "ruff",
    name = "ruff",
    files = "^brave_api|^tests|^examples|^docs",
    args = ["--fix"]
  },
  {
    id = "ruff-format",
    files = "^brave_api|^tests|^examples|^docs"
  }
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v5.0.0"
hooks = [
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" }
]

[[repos]]
repo = "https://github.com/pre-commit/mirrors-mypy"
rev = "v1.15.0"
hooks = [
  {
    id = "mypy",
    additional_dependencies = ["pydantic"]
  }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "tests",
    name = "tests",
    entry = "uv run pytest tests",
    language = "system",
    types = ["python"],
    pass_filenames = false
  },
    {
    id = "just_format",
    name = "just_format",
    entry = "just --unstable --fmt",
    language = "system",
    pass_filenames = false
    }
]
